'use strict';window.DOMHandler=class{constructor(f,h){this._iRuntime=f;this._componentId=h;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(f,h,g,p){this._iRuntime.PostToRuntimeComponent(this._componentId,f,h,g,p)}PostToRuntimeAsync(f,h,g,p){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,f,h,g,p)}_PostToRuntimeMaybeSync(f,h,g){this._iRuntime.UsesWorker()?this.PostToRuntime(f,h,g):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:f,dispatchOpts:g||null,data:h,responseId:null})}AddRuntimeMessageHandler(f,h){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,f,h)}AddRuntimeMessageHandlers(f){for(const [h,g]of f)this.AddRuntimeMessageHandler(h,g)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(f,h){this._callback=f;this._interval=h;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(f){this._canRunImmediate=!!f}Call(){if(-1===this._timerId){var f=Date.now(),h=f-this._lastCallTime,g=this._interval;h>=g&&this._canRunImmediate?(this._lastCallTime=f,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(g-h,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(f,h){super(f,h);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",g=>this._OnCreate(g)],["destroy",g=>this._OnDestroy(g)],["set-visible",g=>this._OnSetVisible(g)],["update-position",g=>this._OnUpdatePosition(g)],["update-state",g=>this._OnUpdateState(g)],["focus",g=>this._OnSetFocus(g)],["set-css-style",g=>this._OnSetCssStyle(g)],["set-attribute",g=>this._OnSetAttribute(g)],["remove-attribute",
g=>this._OnRemoveAttribute(g)]]);this.AddDOMElementMessageHandler("get-element",g=>g)}SetAutoAttach(f){this._autoAttach=!!f}AddDOMElementMessageHandler(f,h){this.AddRuntimeMessageHandler(f,g=>{const p=this._elementMap.get(g.elementId);return h(p,g)})}_OnCreate(f){const h=f.elementId,g=this.CreateElement(h,f);this._elementMap.set(h,g);f.isVisible||(g.style.display="none");f=this._GetFocusElement(g);f.addEventListener("focus",p=>this._OnFocus(h));f.addEventListener("blur",p=>this._OnBlur(h));this._autoAttach&&
document.body.appendChild(g)}CreateElement(f,h){throw Error("required override");}DestroyElement(f){}_OnDestroy(f){f=f.elementId;const h=this._elementMap.get(f);this.DestroyElement(h);this._autoAttach&&h.parentElement.removeChild(h);this._elementMap.delete(f)}PostToRuntimeElement(f,h,g){g||(g={});g.elementId=h;this.PostToRuntime(f,g)}_PostToRuntimeElementMaybeSync(f,h,g){g||(g={});g.elementId=h;this._PostToRuntimeMaybeSync(f,g)}_OnSetVisible(f){this._autoAttach&&(this._elementMap.get(f.elementId).style.display=
f.isVisible?"":"none")}_OnUpdatePosition(f){if(this._autoAttach){var h=this._elementMap.get(f.elementId);h.style.left=f.left+"px";h.style.top=f.top+"px";h.style.width=f.width+"px";h.style.height=f.height+"px";f=f.fontSize;null!==f&&(h.style.fontSize=f+"em")}}_OnUpdateState(f){const h=this._elementMap.get(f.elementId);this.UpdateState(h,f)}UpdateState(f,h){throw Error("required override");}_GetFocusElement(f){return f}_OnFocus(f){this.PostToRuntimeElement("elem-focused",f)}_OnBlur(f){this.PostToRuntimeElement("elem-blurred",
f)}_OnSetFocus(f){const h=this._GetFocusElement(this._elementMap.get(f.elementId));f.focus?h.focus():h.blur()}_OnSetCssStyle(f){this._elementMap.get(f.elementId).style[f.prop]=f.val}_OnSetAttribute(f){this._elementMap.get(f.elementId).setAttribute(f.name,f.val)}_OnRemoveAttribute(f){this._elementMap.get(f.elementId).removeAttribute(f.name)}GetElementById(f){return this._elementMap.get(f)}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let h=0;function g(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.isStringSrc?new Promise(d=>{const e="c3_resolve_"+h;++h;self[e]=d;a.textContent=c.str+`\n\nself["${e}"]();`;document.head.appendChild(a)}):new Promise((d,e)=>{a.onload=d;a.onerror=e;a.src=c;document.head.appendChild(a)})}let p=!1,A=!1;function E(){if(!p){try{new Worker("blob://",{get type(){A=!0}})}catch(c){}p=!0}return A}
const F=/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let t=new Audio;const u={"audio/webm; codecs=opus":!!t.canPlayType("audio/webm; codecs=opus")&&!F,"audio/ogg; codecs=opus":!!t.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!t.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!t.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!t.canPlayType("audio/mp4"),"audio/mpeg":!!t.canPlayType("audio/mpeg")};t=null;
async function G(c){c=await C(c);return(new TextDecoder("utf-8")).decode(c)}function C(c){return new Promise((a,d)=>{const e=new FileReader;e.onload=k=>a(k.target.result);e.onerror=k=>d(k);e.readAsArrayBuffer(c)})}const v=[];let w=0;window.RealFile=window.File;const x=[],B=new Map,r=new Map;let D=0;const y=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");y.push(c)};const H=new Set(["cordova","playable-ad","instant-games"]);function I(c){return H.has(c)}
let b=!1;window.RuntimeInterface=class c{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;this._isFileProtocol="file"===location.protocol.substr(0,4);!this._useWorker||"undefined"!==
typeof OffscreenCanvas&&navigator.userActivation&&E()||(this._useWorker=!1);if("playable-ad"===this._exportType||"instant-games"===this._exportType)this._useWorker=!1;if("cordova"===this._exportType&&this._useWorker)if(/android/i.test(navigator.userAgent)){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);d&&90<=parseInt(d[1],10)||(this._useWorker=!1)}else this._useWorker=!1;this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||!this._isFileProtocol||
alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",d=>this._OnCordovaFetchLocalFile(d));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",d=>this._OnCreateJobWorker(d));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();
this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsFileProtocol(){return this._isFileProtocol}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return f&&
"cordova"===this._exportType}IsiOSWebView(){const a=navigator.userAgent;return f&&I(this._exportType)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}async _Init(a){"macos-wkwebview"===this._exportType&&this._SendWrapperMessage({type:"ready"});if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let e=0,k=a.engineScripts.length;e<k;++e){var d=a.engineScripts[e].toLowerCase();this._localFileStrings.hasOwnProperty(d)?
a.engineScripts[e]={isStringSrc:!0,str:this._localFileStrings[d]}:this._localFileBlobs.hasOwnProperty(d)&&(a.engineScripts[e]=URL.createObjectURL(this._localFileBlobs[d]))}}a.baseUrl?this._baseUrl=a.baseUrl:(d=location.origin,this._baseUrl=("null"===d?"file:///":d)+location.pathname,d=this._baseUrl.lastIndexOf("/"),-1!==d&&(this._baseUrl=this._baseUrl.substr(0,d+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);d=new MessageChannel;this._messageChannelPort=d.port1;this._messageChannelPort.onmessage=
e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this._OnMessageFromDebugger(e));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,d.port2):await this._InitDOM(a,d.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?
this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,d,e){if(a.startsWith("blob:"))return new Worker(a,e);if("cordova"===this._exportType&&this._isFileProtocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(e.isC3MainWorker?
a:this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),e);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),e)}return new Worker(a,e)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),
windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:c.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),
supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isFileProtocol:this._isFileProtocol,isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,d){var e=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(e,this._baseUrl,{type:"module",name:"Runtime",isC3MainWorker:!0});
this._canvas=document.createElement("canvas");this._canvas.style.display="none";e=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;let k=a.workerDependencyScripts||[],m=a.engineScripts;k=await Promise.all(k.map(l=>this._MaybeGetCordovaScriptURL(l)));m=await Promise.all(m.map(l=>this._MaybeGetCordovaScriptURL(l)));if("cordova"===this._exportType)for(let l=0,n=a.projectScripts.length;l<n;++l){const q=a.projectScripts[l],z=q[0];if(z===a.mainProjectScript||
"scriptsInEvents.js"===z||z.endsWith("/scriptsInEvents.js"))q[1]=await this._MaybeGetCordovaScriptURL(z)}this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:k,engineScripts:m,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=x.map(l=>new l(this));this._FindRuntimeDOMHandler();
self.c3_callFunction=(l,n)=>this._runtimeDomHandler._InvokeFunctionFromJS(l,n);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,d){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=x.map(l=>new l(this));this._FindRuntimeDOMHandler();var e=a.engineScripts.map(l=>"string"===typeof l?(new URL(l,
this._baseUrl)).toString():l);Array.isArray(a.workerDependencyScripts)&&e.unshift(...a.workerDependencyScripts);e=await Promise.all(e.map(l=>this._MaybeGetCordovaScriptURL(l)));await Promise.all(e.map(l=>g(l)));e=self.C3_ProjectScriptsStatus;const k=a.mainProjectScript,m=a.projectScripts;for(let [l,n]of m)if(n||(n=l),l===k)try{n=await this._MaybeGetCordovaScriptURL(n),await g(n),"preview"!==this._exportType||e[l]||this._ReportProjectMainScriptError(l,"main script did not run to completion")}catch(q){this._ReportProjectMainScriptError(l,
q)}else if("scriptsInEvents.js"===l||l.endsWith("/scriptsInEvents.js"))n=await this._MaybeGetCordovaScriptURL(n),await g(n);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),
{isInWorker:!1,messagePort:d,canvas:this._canvas,runOnStartupFunctions:y}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectMainScriptError(a,d){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,d,e,k,m){this._messageChannelPort.postMessage({type:"event",component:a,handler:d,dispatchOpts:k||null,data:e,responseId:null},m)}PostToRuntimeComponentAsync(a,
d,e,k,m){const l=D++,n=new Promise((q,z)=>{r.set(l,{resolve:q,reject:z})});this._messageChannelPort.postMessage({type:"event",component:a,handler:d,dispatchOpts:k||null,data:e,responseId:l},m);return n}["_OnMessageFromRuntime"](a){const d=a.type;if("event"===d)return this._OnEventFromRuntime(a);if("result"===d)this._OnResultFromRuntime(a);else if("runtime-ready"===d)this._OnRuntimeReady();else if("alert-error"===d)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===d)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${d}'`);}_OnEventFromRuntime(a){const d=a.component,e=a.handler,k=a.data,m=a.responseId;if(a=B.get(d))if(a=a.get(e)){var l=null;try{l=a(k)}catch(n){console.error(`Exception in '${d}' handler '${e}':`,n);null!==m&&this._PostResultToRuntime(m,!1,""+n);return}if(null===m)return l;l&&l.then?l.then(n=>this._PostResultToRuntime(m,!0,n)).catch(n=>{console.error(`Rejection from '${d}' handler '${e}':`,n);this._PostResultToRuntime(m,!1,""+n)}):this._PostResultToRuntime(m,
!0,l)}else console.warn(`[DOM] No handler '${e}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}_PostResultToRuntime(a,d,e){let k;e&&e.transferables&&(k=e.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:d,result:e},k)}_OnResultFromRuntime(a){const d=a.responseId,e=a.isOk;a=a.result;const k=r.get(d);e?k.resolve(a):k.reject(a);r.delete(d)}AddRuntimeComponentMessageHandler(a,d,e){let k=B.get(a);k||(k=new Map,B.set(a,k));if(k.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);
k.set(d,e)}static AddDOMHandlerClass(a){if(x.includes(a))throw Error("DOM handler already added");x.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||b)}static _SetWrapperIsFullscreenFlag(a){b=!!a}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&
this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!u[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a){return"cordova"===this._exportType&&(a.startsWith("file:")||this._isFileProtocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),
a=new Blob([a],{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const d=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(d);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(d);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,
d){a=a[d];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const d=this._GetPermissionAPI();return new Promise((e,k)=>d.checkPermission(this._MapPermissionID(d,a),m=>e(!!m.hasPermission),k))}_RequestPermission(a){const d=this._GetPermissionAPI();return new Promise((e,k)=>d.requestPermission(this._MapPermissionID(d,a),m=>e(!!m.hasPermission),k))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const d of a)if(!await this._HasPermission(d)&&
!1===await this._RequestPermission(d))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const d=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((e,k)=>{window.resolveLocalFileSystemURL(d,m=>{m.file(e,k)},k)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await G(a)}_CordovaMaybeStartNextArrayBufferRead(){if(v.length&&!(8<=w)){w++;
var a=v.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((d,e)=>{v.push({filename:a,successCallback:k=>{w--;this._CordovaMaybeStartNextArrayBufferRead();d(k)},errorCallback:k=>{w--;this._CordovaMaybeStartNextArrayBufferRead();e(k)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,d,e){try{const k=await this.CordovaFetchLocalFile(a),m=await C(k);
d(m)}catch(k){e(k)}}_SendWrapperMessage(a){if("windows-webview2"===this._exportType)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this._exportType)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async _ConvertDataUrisToBlobs(){const a=[];for(const [d,e]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(d,e));await Promise.all(a)}async _ConvertDataUriToBlobs(a,d){if("object"===
typeof d)this._localFileBlobs[a]=new Blob([d.str],{type:d.type}),this._localFileStrings[a]=d.str;else{let e=await this._FetchDataUri(d);e||(e=this._DataURIToBinaryBlobSync(d));this._localFileBlobs[a]=e}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",d),null}}_DataURIToBinaryBlobSync(a){a=
this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var e=a.substring(5,d);a=a.substring(d+1);d=e.split(";");e=d[0]||"";const k=d[2];a="base64"===d[1]||"base64"===k?atob(a):decodeURIComponent(a);return{mime_type:e,data:a}}_BinaryStringToBlob(a,d){var e=a.length;let k=e>>2,m=new Uint8Array(e),l=new Uint32Array(m.buffer,0,k),n,q;for(q=n=0;n<k;++n)l[n]=a.charCodeAt(q++)|a.charCodeAt(q++)<<
8|a.charCodeAt(q++)<<16|a.charCodeAt(q++)<<24;for(e&=3;e--;)m[q]=a.charCodeAt(q),++q;return new Blob([m],{type:d})}}}"use strict";
{const f=self.RuntimeInterface;function h(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const g=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),p={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},A={dispatchUserScriptEvent:!0},E={dispatchRuntimeEvent:!0};function F(b){return new Promise((c,a)=>{const d=document.createElement("link");d.onload=()=>c(d);d.onerror=
e=>a(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function t(b){return new Promise((c,a)=>{const d=new Image;d.onload=()=>c(d);d.onerror=e=>a(e);d.src=b})}async function u(b){b=URL.createObjectURL(b);try{return await t(b)}finally{URL.revokeObjectURL(b)}}function G(b){return new Promise((c,a)=>{let d=new FileReader;d.onload=e=>c(e.target.result);d.onerror=e=>a(e);d.readAsText(b)})}async function C(b,c,a){if(!/firefox/i.test(navigator.userAgent))return await u(b);var d=await G(b);d=
(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const k=e.getAttribute("width"),m=e.getAttribute("height");if(!k.includes("%")&&!m.includes("%"))return await u(b)}e.setAttribute("width",c+"px");e.setAttribute("height",a+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await u(b)}function v(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const w=new Set(["input","textarea","datalist","select"]);function x(b){return w.has(b.tagName.toLowerCase())||v(b)}const B=new Set(["canvas","body","html"]);function r(b){const c=b.target.tagName.toLowerCase();B.has(c)&&b.preventDefault()}function D(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await u(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";
document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(b,c,a,d,e){b=await C(b,c,a);const k=document.createElement("canvas");k.width=d;k.height=e;k.getContext("2d").drawImage(b,0,0,c,a);return k};let y=!1;document.addEventListener("pause",()=>y=!0);document.addEventListener("resume",()=>y=!1);function H(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function I(){const b=
document.activeElement;if(!b)return!1;const c=b.tagName.toLowerCase(),a=new Set("email number password search tel text url".split(" "));return"textarea"===c?!0:"input"===c?a.has(b.type.toLowerCase()||"text"):v(b)}f.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=
this._debugHighlightElem=null;b.AddRuntimeComponentMessageHandler("canvas","update-size",d=>this._OnUpdateCanvasSize(d));b.AddRuntimeComponentMessageHandler("runtime","invoke-download",d=>this._OnInvokeDownload(d));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",d=>this._OnRasterSvgImage(d));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",d=>this._OnGetSvgImageSize(d));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",d=>this._OnSetTargetOrientation(d));
b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",d=>this._OnPostToDebugger(d));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",d=>this._OnPostToDebugger(d));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",d=>this._OnDebugHighlight(d));b.AddRuntimeComponentMessageHandler("runtime",
"enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",d=>this._OnAddStylesheet(d));b.AddRuntimeComponentMessageHandler("runtime","alert",d=>this._OnAlert(d));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",
d=>{const e=d.target,k=e.tagName.toLowerCase();c.has(k)||v(e)||d.preventDefault()});const a=b.GetCanvas();window.addEventListener("selectstart",r);window.addEventListener("gesturehold",r);a.addEventListener("selectstart",r);a.addEventListener("gesturehold",r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),a.addEventListener("pointerdown",r)):a.addEventListener("touchstart",r);this._mousePointerLastButtons=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",D,{passive:!1});window.addEventListener("wheel",D,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",
d=>this._OnFullscreenError(d));window.addEventListener("webkitfullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("mozfullscreenerror",d=>this._OnFullscreenError(d));b.IsiOSWebView()&&window.addEventListener("focusout",()=>{I()||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this._OnWrapperMessage(d);this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?
(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!y)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:H()});this._mousePointerLastButtons=0});window.addEventListener("focusin",
c=>{x(c.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",c=>this._OnKeyEvent("keydown",c));window.addEventListener("keyup",c=>this._OnKeyEvent("keyup",c));window.addEventListener("dblclick",c=>this._OnMouseEvent("dblclick",c,p));window.addEventListener("wheel",c=>this._OnMouseWheelEvent("wheel",c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this._HandlePointerDownFocus(c);this._OnPointerEvent("pointerdown",c)}),this._iRuntime.UsesWorker()&&
"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",c=>this._OnPointerRawUpdate(c))):window.addEventListener("pointermove",c=>this._OnPointerEvent("pointermove",c)),window.addEventListener("pointerup",c=>this._OnPointerEvent("pointerup",c)),window.addEventListener("pointercancel",c=>this._OnPointerEvent("pointercancel",
c))):(window.addEventListener("mousedown",c=>{this._HandlePointerDownFocus(c);this._OnMouseEventAsPointer("pointerdown",c)}),window.addEventListener("mousemove",c=>this._OnMouseEventAsPointer("pointermove",c)),window.addEventListener("mouseup",c=>this._OnMouseEventAsPointer("pointerup",c)),window.addEventListener("touchstart",c=>{this._HandlePointerDownFocus(c);this._OnTouchEvent("pointerdown",c)}),window.addEventListener("touchmove",c=>this._OnTouchEvent("pointermove",c)),window.addEventListener("touchend",
c=>this._OnTouchEvent("pointerup",c)),window.addEventListener("touchcancel",c=>this._OnTouchEvent("pointercancel",c)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}_PostRuntimeEvent(b,c){this.PostToRuntime(b,c||null,E)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const b=
this._GetWindowInnerWidth(),c=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,c,0))}_ScheduleSimulatedResize(b,c,a){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>
this._OnSimulatedResize(b,c,a),48)}_OnSimulatedResize(b,c,a){const d=this._GetWindowInnerWidth(),e=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;d!=b||e!=c?this._PostRuntimeEvent("window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.IsDocumentFullscreen()}):10>a&&this._ScheduleSimulatedResize(d,e,a+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}_OnFullscreenChange(){const b=
f.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",b);this.PostToRuntime("fullscreenerror",{isFullscreen:f.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():
this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,c){"Backspace"===c.key&&r(c);const a=g.get(c.code)||c.code;this._PostToRuntimeMaybeSync(b,{code:a,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},p)}_OnMouseWheelEvent(b,c){this.PostToRuntime(b,{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,
timeStamp:c.timeStamp},p)}_OnMouseEvent(b,c,a){h(c)||this._PostToRuntimeMaybeSync(b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},a)}_OnMouseEventAsPointer(b,c){if(!h(c)){var a=this._mousePointerLastButtons;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,
clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},p);this._mousePointerLastButtons=c.buttons;this._OnMouseEvent(c.type,c,A)}}_OnPointerEvent(b,c){this._pointerRawUpdateRateLimiter&&"pointermove"!==b&&this._pointerRawUpdateRateLimiter.Reset();var a=0;"mouse"===c.pointerType&&(a=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,
lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},p);"mouse"===c.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this._OnMouseEvent(a,c,A),this._mousePointerLastButtons=c.buttons)}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",
this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,c){for(let a=0,d=c.changedTouches.length;a<d;++a){const e=c.changedTouches[a];this._PostToRuntimeMaybeSync(b,{pointerId:e.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:2*(e.radiusX||e.webkitRadiusX||0),height:2*(e.radiusY||e.webkitRadiusY||0),pressure:e.force||e.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:e.rotationAngle||
0,timeStamp:c.timeStamp},p)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",
b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},
p)}_OnDeviceOrientationAbsolute(b){this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},p)}_OnDeviceMotion(b){let c=null;var a=b.acceleration;a&&(c={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var d=b.accelerationIncludingGravity;d&&(a={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const e=b.rotationRate;e&&(d={alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0});this.PostToRuntime("devicemotion",{acceleration:c,accelerationIncludingGravity:a,
rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},p)}_OnUpdateCanvasSize(b){const c=this.GetRuntimeInterface().GetCanvas();c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";this._isFirstSizeUpdate&&(c.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(b){const c=b.url;b=b.filename;const a=document.createElement("a"),d=document.body;a.textContent=b;a.href=c;a.download=b;d.appendChild(a);a.click();
d.removeChild(a)}async _OnRasterSvgImage(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await F(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const c of b)(b=
c.play())&&b.catch(a=>{this._mediaRemovedPendingPlay.has(c)||this._mediaPendingPlay.add(c)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(b);let c;try{c=b.play()}catch(a){this._mediaPendingPlay.add(b);return}c&&c.catch(a=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var c=this._debugHighlightElem;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display=
"none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,c){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:c})}_OnAlert(b){alert(b.message)}_OnWrapperMessage(b){"entered-fullscreen"===b?(f._SetWrapperIsFullscreenFlag(!0),this._OnFullscreenChange()):"exited-fullscreen"===b?(f._SetWrapperIsFullscreenFlag(!1),this._OnFullscreenChange()):console.warn("Unknown wrapper message: ",
b)}})}"use strict";
self.JobSchedulerDOM=class{constructor(f){this._runtimeInterface=f;this._baseUrl=f.GetBaseURL();"preview"===f.GetExportType()?this._baseUrl+="workers/":this._baseUrl+=f.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var f=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(f,this._baseUrl,{name:"DispatchWorker"});f=new MessageChannel;this._inputPort=f.port1;this._dispatchWorker.postMessage({type:"_init","in-port":f.port2},[f.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const f=this._jobWorkers.length;var h=this._runtimeInterface._GetWorkerURL("jobworker.js");h=await this._runtimeInterface.CreateWorker(h,this._baseUrl,{name:"JobWorker"+f});const g=new MessageChannel,p=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:g.port1},[g.port1]);h.postMessage({type:"init",number:f,"dispatch-port":g.port2,"output-port":p.port2},[g.port2,p.port2]);this._jobWorkers.push(h);return p.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));
